title: aaaaaaaa
author: Superchurro - frituras mendoza
email: superchurro@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hacemos churros caseros de 15cm con mucho dulce de leche y mucho amor

# social links
twitter_username: @superchurro # DO NOT include the @ character, or else the build will fail!
github_username:  superchurro.github.io # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
